#ifndef CONSTANTS_H__
#define CONSTANTS_H__

#define ARGS_LEN_SUM_MULTIPLY 5
#define ARGS_LEN_SOLVE 4

#define ARGS_ACTION_INDEX 1
#define ARGS_FIRST_FILE_MATRIX_INDEX 2
#define ARGS_SECOND_FILE_MATRIX_INDEX 3
#define ARGS_RES_FILE_MATRIX_INDEX 4
#define ARGS_RES_FILE_MATRIX_INDEX_SOLVE 3
#define MATRIX_SUM "a"
#define MATRIX_MULTI "m"
#define MATRIX_SOLVE "o"

#define MINUS_CONSTANT -1.0
#define REVERSE_CONSTANT 1.0

#define MATRIX_EQUALS 1

#define EPSILON 1e-8
#endif
